default: main.o Temperatures.o
	g++ main.o Temeperatures.o -o M05Lab2
main.o: main.cpp
	g++ -std=c++14 -c main.cpp
Temperatures.o: Temperatures.cpp
	g++ -std=c++14 -c Temeperatures.cpp
run:
	./M05Lab2
